version: '3.3'

networks:
  aw-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  postgres_data:

services:
  prometheus:
    image: prom/prometheus
    container_name: poc_prometheus_hexagonal
    volumes:
      - ./application/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aw-network
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: poc_grafana_hexagonal
    ports:
      - 3000:3000
    networks:
      - aw-network
  postgres:
    image: postgres:12-alpine
    container_name: poc_postgres_hexagonal
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=poc_hexagonal_db"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aw-network