spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:poc-hexagonal-test
    username: sa
    password:
#    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
  mvc:
    pathmatch-strategy: ant-path-matcher

management:
  endpoints:
    web:
      exposure:
        include: '*'
