server:
  port: 8080
  servlet:
    contextPath: /hexagonal
  undertow:
    threads:
      io: 5
      worker: 5
    accesslog:
      enabled: true
      pattern: "%t %a %r %s (%D ms)"
      dir: C:/temp/logs
    options:
      server:
        record-request-start-time: true
spring:
  application:
    name: poc-hexagonal
  datasource:
    url: jdbc:postgresql://localhost:5432/poc_hexagonal_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    generate-ddl: true
    show_sql: true
    hibernate:
      dll-auto: update

  mvc:
    pathmatch-strategy: ant-path-matcher

logging:
  level:
    web: DEBUG

management:
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enableb-by-default: false
    web:
      exposure:
        include: 'health,prometheus'


