server:
  port: 8080
  servlet:
    contextPath: /hexagonal
  undertow:
    threads:
      io: 5
      worker: 5
    accesslog:
      enabled: true
      pattern: "%t %a %r %s (%D ms)"
      dir: C:/temp/logs
    options:
      server:
        record-request-start-time: true
spring:
  application:
    name: poc-hexagonal

logging:
  level:
    web: DEBUG

management:
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enableb-by-default: false
    web:
      exposure:
        include: 'health,prometheus'


